config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/product.rb
class Product < ApplicationRecord
	has_and_belongs_to_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :find_product, only: [:edit, :update, :destroy]

  def index
  	@products = Product.includes(:categories)
  end

  def new
  	@product = Product.new

  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to products_path
  	else
  		render :new
  	end
  end

  def edit
    
  end

  def update
  	if @product.update(product_params)
  		redirect_to products_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@product.destroy
  	redirect_to products_path
  end

  private

  def find_product
      @product = Product.find(params[:id])
    end
  #Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, category_ids: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container ">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<h1><strong><%= action %> Producto</strong></h1>
			<%= form_for(@product) do |product| %>
			<div class="form-group">
				<%= product.text_field :name, class: 'form-control', placeholder: 'Ingrese el nombre' %>
			</div>
			<div class="form-group">
				<%= product.text_field :price, class: 'form-control', placeholder: 'Ingrese el precio' %>
			</div>
			<div class="form-group">
				<%= hidden_field_tag "product[category_ids][]", nil %>
				<% Category.all.each do  |category|  %>
				<%= check_box_tag "product[category_ids][]", category.id, @product.category_ids.include?(category.id), id: dom_id(category) %>
				<%= label_tag dom_id(category), category.name %><br>
				<% end %>
			</div>

			<div class="actions">
				<%= product.submit 'Guardar Producto', class: 'btn btn-primary btn-block' %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/products/edit.html.erb
<%= render 'form', action: 'Editar' %>

app/views/products/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h1>Productos</h1>
			
			<div class="text-right">
        		<%= link_to "Crear Producto", new_product_path, class: "btn btn-primary" %>
      </div>
				<table class="table">
					<thead>
						<th>Nombre</th>
						<th>Precio</th>
						<th>Categorías</th>
						<th></th>
					</thead>
					<tbody>
					<% @products.each do |product| %>
						<tr>
							<td><%= product.name %></td>
							<td><%= product.price %></td>
							<td>
                				<%= product.categories.collect(&:name).join(",") %>
              				</td>
							<td>
		 			
							 <%= link_to 'Edit', edit_product_path(product),class: "btn btn-info" %> -
							  <%= link_to 'Remove', product, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure to delete this product?' } %>
							</td>
						</tr>
					<% end %>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/products/new.html.erb
<%= render 'form', action: 'Crear' %>